-- Airbeat One v22: mehrere gemeinsame Treffpunkte

create table if not exists public.meeting_points (
  id bigint generated by default as identity primary key,
  title text not null,
  location text not null,
  meeting_time timestamptz not null,
  created_by text not null,
  note text,
  created_at timestamptz default now()
);

alter table public.meeting_points enable row level security;

drop policy if exists "meeting points lesen" on public.meeting_points;
drop policy if exists "meeting points hinzufügen" on public.meeting_points;
drop policy if exists "meeting points löschen" on public.meeting_points;

create policy "meeting points lesen"
on public.meeting_points
for select
to anon
using (true);

create policy "meeting points hinzufügen"
on public.meeting_points
for insert
to anon
with check (true);

create policy "meeting points löschen"
on public.meeting_points
for delete
to anon
using (true);

grant select, insert, delete on table public.meeting_points to anon;
grant usage, select on all sequences in schema public to anon;
