-- Airbeat One v24: Festival-Momente / Fotogalerie
-- Erstellt Tabelle + öffentlichen Storage-Bucket + Richtlinien

create table if not exists public.festival_photos (
  id bigint generated by default as identity primary key,
  storage_path text not null unique,
  public_url text not null,
  caption text,
  uploaded_by text not null,
  created_at timestamptz default now()
);

alter table public.festival_photos enable row level security;

drop policy if exists "festival photos lesen" on public.festival_photos;
drop policy if exists "festival photos hinzufügen" on public.festival_photos;
drop policy if exists "festival photos löschen" on public.festival_photos;

create policy "festival photos lesen"
on public.festival_photos
for select
to anon
using (true);

create policy "festival photos hinzufügen"
on public.festival_photos
for insert
to anon
with check (true);

create policy "festival photos löschen"
on public.festival_photos
for delete
to anon
using (true);

grant select, insert, delete on table public.festival_photos to anon;
grant usage, select on all sequences in schema public to anon;

insert into storage.buckets (id, name, public)
values ('festival-moments', 'festival-moments', true)
on conflict (id) do update set public = true;

drop policy if exists "festival moments ansehen" on storage.objects;
drop policy if exists "festival moments hochladen" on storage.objects;
drop policy if exists "festival moments löschen" on storage.objects;

create policy "festival moments ansehen"
on storage.objects
for select
to anon
using (bucket_id = 'festival-moments');

create policy "festival moments hochladen"
on storage.objects
for insert
to anon
with check (bucket_id = 'festival-moments');

create policy "festival moments löschen"
on storage.objects
for delete
to anon
using (bucket_id = 'festival-moments');
