-- In Supabase SQL Editor ausführen

create table if not exists public.timetable (
  id bigint generated by default as identity primary key,
  day text not null,
  time time not null,
  act text not null,
  name text,
  created_at timestamptz default now()
);

create table if not exists public.crew_settings (
  id bigint primary key,
  meeting_point text,
  notes text,
  updated_at timestamptz default now()
);

alter table public.timetable enable row level security;
alter table public.crew_settings enable row level security;

drop policy if exists "public timetable read" on public.timetable;
drop policy if exists "public timetable insert" on public.timetable;
drop policy if exists "public timetable delete" on public.timetable;
drop policy if exists "public crew read" on public.crew_settings;
drop policy if exists "public crew upsert insert" on public.crew_settings;
drop policy if exists "public crew update" on public.crew_settings;

create policy "public timetable read" on public.timetable for select to anon using (true);
create policy "public timetable insert" on public.timetable for insert to anon with check (true);
create policy "public timetable delete" on public.timetable for delete to anon using (true);

create policy "public crew read" on public.crew_settings for select to anon using (true);
create policy "public crew upsert insert" on public.crew_settings for insert to anon with check (true);
create policy "public crew update" on public.crew_settings for update to anon using (true) with check (true);
