-- Airbeat One v18: Chat-Tabelle + Rechte

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null check (char_length(message) <= 500),
  created_at timestamptz default now()
);

alter table public.chat_messages enable row level security;

drop policy if exists "chat lesen" on public.chat_messages;
drop policy if exists "chat schreiben" on public.chat_messages;

create policy "chat lesen"
on public.chat_messages
for select
to anon
using (true);

create policy "chat schreiben"
on public.chat_messages
for insert
to anon
with check (true);

grant select, insert on table public.chat_messages to anon;
grant usage, select on all sequences in schema public to anon;
